### ISSUE TITLE
ERROR ITMS-90535 - Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by wavs** [VidCoin/VidCoin-iOS-SDK#2]
Hi,

Using Xcode 7 GM, I've tried to publish an app including VidCoin SDK 1.3.0 to iTunesConnect. During submission, iTunesConnect returns me this error:

<img width="588" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2640563/10014027/b7301e50-6116-11e5-80bf-626e25b7c948.png">

As a workaround, I remove the key "CFBundleExecutable" from the VidCoin.bundle.

**Comment by RobinDCXP** [comment]
Hi @wavs.

Thanks again for your feedback. This correction will be included in our fix release, coming out this Thursday.

Thank you for your patience.

**Comment by RobinDCXP** [comment]
Issue #2 fixed in release v1.3.1.
